name: GitHub Classroom Workflow

on:
  push

jobs:
  build:
    name: Autograding
    runs-on: macos-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.0
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.1'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - uses: education/autograding@v1